//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paquetes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paquetes()
        {
            this.PaquetePuntoDeControlSet = new HashSet<PaquetePuntoDeControlSet>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string Codigo { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public int TrayectoId { get; set; }
        public int RemitenteId { get; set; }
        public int DestinatarioId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaquetePuntoDeControlSet> PaquetePuntoDeControlSet { get; set; }
        public virtual Trayectos Trayectos { get; set; }
        public virtual Usuarios Remitente { get; set; }
        public virtual Usuarios Destinatario { get; set; }
    }
}
