//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paquete
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string Codigo { get; set; }
        public string CodigoExterno { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<bool> Entregado { get; set; }
        public Nullable<int> HoraDeEntrega { get; set; }
        public int TrayectoId { get; set; }
        public int RemitenteId { get; set; }
        public int DestinatarioId { get; set; }
        public int PuntoDeControlId { get; set; }
        public bool Borrado { get; set; }
    
        public virtual Trayecto Trayecto { get; set; }
        public virtual Usuario Remitente { get; set; }
        public virtual Usuario Destinatario { get; set; }
        public virtual PuntoDeControl PDC_Actual { get; set; }
    }
}
