//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaquetePuntoDeControlSet
    {
        public int Id { get; set; }
        public System.DateTime FechaLlegada { get; set; }
        public int IdPaquete { get; set; }
        public int IdPuntoDeControl { get; set; }
    
        public virtual Paquetes Paquetes { get; set; }
        public virtual PuntosDeControl PuntosDeControl { get; set; }
    }
}
