//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntosDeControl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PuntosDeControl()
        {
            this.PaquetePuntoDeControlSet = new HashSet<PaquetePuntoDeControlSet>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Posicion { get; set; }
        public int TiempoEstimado { get; set; }
        public Nullable<int> IdAgencia { get; set; }
        public int IdTrayecto { get; set; }
    
        public virtual Agencias Agencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaquetePuntoDeControlSet> PaquetePuntoDeControlSet { get; set; }
        public virtual Trayectos Trayectos { get; set; }
    }
}
