//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntoDeControl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PuntoDeControl()
        {
            this.Paquetes = new HashSet<Paquete>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Posicion { get; set; }
        public int TiempoEstimado { get; set; }
        public Nullable<int> IdAgencia { get; set; }
        public int IdTrayecto { get; set; }
        public string CodigoExterno { get; set; }
        public bool Borrado { get; set; }
    
        public virtual Agencia Agencia { get; set; }
        public virtual Trayecto Trayecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paquete> Paquetes { get; set; }
    }
}
