//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trayectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trayectos()
        {
            this.Paquetes = new HashSet<Paquetes>();
            this.PuntosDeControl = new HashSet<PuntosDeControl>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int idAgenciaOrigen { get; set; }
        public int idAgenciaDestino { get; set; }
    
        public virtual Agencias Origen { get; set; }
        public virtual Agencias Destino { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paquetes> Paquetes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuntosDeControl> PuntosDeControl { get; set; }
    }
}
